### PR TITLE
Crosssection viewer

### PR DESCRIPTION
**Pull request by jenshnielsen**
Simple GUI for showing cross sections of 2d plots

### CODE REVIEW

**Comment by giulioungaretti** [comment]
We should definitely add an option to save the subplots separately.

**Comment by giulioungaretti** [comment]
and, does it also work for say a vna trace ?

**Comment by jenshnielsen** [comment]
The vna trace should be exactly the same as this one, provided that the sync bug is fixed

There is not really a simple way of saving individual subplots in matplotlib. But we can hack something along the lines of http://stackoverflow.com/questions/4325733/save-a-subplot-in-matplotlib into the code

**Comment by giulioungaretti** [comment]
@jenshnielsen  sync should be fixed, no?
Yes, that looks  ok!

**Comment by jenshnielsen** [comment]
Yes sync is fixed but not retrospectively for old data sets

**Comment by giulioungaretti** [comment]
oh well.

**Comment by giulioungaretti** [comment]
Can't seem to get it to work.  Do you have example notebook that goes with this ?

**Comment by giulioungaretti** [comment]
@jenshnielsen  let's keep this on hold for now .

**Comment by giulioungaretti** [comment]
@jenshnielsen feel free to merge when you feel like it's ready@

**Comment by jenshnielsen** [comment]
Just need to fix a few more label -> label + unit transitions and it should be ok to merge

**Comment by giulioungaretti** [comment]
nice! How about usage tho? When should this GUI pop-up? Should it be manually called ? 

Another note: some of the fixes on the base things ,should either be cherry picked into qcodes, or have been made there to begin with 🦄

**Comment by jenshnielsen** [comment]
I think it should be manually called for now but we should document it's use somewhere

**Pull request merged**
